/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.*;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Patricia
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //private Hospital hospital;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        panel_espera.setBackground(Color.DARK_GRAY);
        panel_vacunacion.setBackground(Color.DARK_GRAY);
        panel_observacion.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void actualizarColaEspera(ArrayList<Paciente> colaEspera) {
        String texto = "";
        for (int i = 0; i < colaEspera.size(); i++) {
            texto = texto + colaEspera.get(i).getIdP() + " ";
        }
        cola_espera.setText(texto);
    }

    public void actualizarSalaDesc(ArrayList<Sanitario> salaDescanso) {
        String texto = "";
        for (int i = 0; i < salaDescanso.size(); i++) {
            texto = texto + salaDescanso.get(i).getIdS() + " ";
        }
        sala_descanso.setText(texto);
    }

    public void actualizarAux(Auxiliar aux) {
        if (aux.getIdA() == "A1") {
            auxiliar1.setText(aux.getIdA());
        } else if (aux.getIdA() == "A2") {
            auxiliar2.setText(aux.getIdA());
        }
    }

    public void actualizarSalaVac(int puesto, Puesto salaVac[]) {
        String texto = "";
        if (salaVac[puesto].isOcupadoS()) {
            texto = texto + salaVac[puesto].getListSanitario().get(0).getIdS();
        }
        if (salaVac[puesto].isOcupadoP()) {
            texto = texto + " " + salaVac[puesto].getListPaciente().get(0).getIdP();
        }
        if (puesto == 0) {
            puesto1_vac.setText(texto);
        } else if (puesto == 1) {
            puesto2_vac.setText(texto);
        } else if (puesto == 2) {
            puesto3_vac.setText(texto);
        } else if (puesto == 3) {
            puesto4_vac.setText(texto);
        } else if (puesto == 4) {
            puesto5_vac.setText(texto);
        } else if (puesto == 5) {
            puesto6_vac.setText(texto);
        } else if (puesto == 6) {
            puesto7_vac.setText(texto);
        } else if (puesto == 7) {
            puesto8_vac.setText(texto);
        } else if (puesto == 8) {
            puesto9_vac.setText(texto);
        } else if (puesto == 9) {
            puesto10_vac.setText(texto);
        }
    }

    public void actualizarSalaObs(int puesto, Puesto salaObs[]) {
        String texto = "";
        if (salaObs[puesto].isOcupadoS()) {
            texto = texto + salaObs[puesto].getListSanitario().get(0).getIdS();
        }
        if (salaObs[puesto].isOcupadoP()) {
            texto = texto + " " + salaObs[puesto].getListPaciente().get(0).getIdP();
        }
        if (puesto == 0) {
            puesto1_obs.setText(texto);
        } else if (puesto == 1) {
            puesto2_obs.setText(texto);
        } else if (puesto == 2) {
            puesto3_obs.setText(texto);
        } else if (puesto == 3) {
            puesto4_obs.setText(texto);
        } else if (puesto == 4) {
            puesto5_obs.setText(texto);
        } else if (puesto == 5) {
            puesto6_obs.setText(texto);
        } else if (puesto == 6) {
            puesto7_obs.setText(texto);
        } else if (puesto == 7) {
            puesto8_obs.setText(texto);
        } else if (puesto == 8) {
            puesto9_obs.setText(texto);
        } else if (puesto == 9) {
            puesto10_obs.setText(texto);
        } else if (puesto == 10) {
            puesto11_obs.setText(texto);
        } else if (puesto == 11) {
            puesto12_obs.setText(texto);
        } else if (puesto == 12) {
            puesto13_obs.setText(texto);
        } else if (puesto == 13) {
            puesto14_obs.setText(texto);
        } else if (puesto == 14) {
            puesto15_obs.setText(texto);
        } else if (puesto == 15) {
            puesto16_obs.setText(texto);
        } else if (puesto == 16) {
            puesto17_obs.setText(texto);
        } else if (puesto == 17) {
            puesto18_obs.setText(texto);
        } else if (puesto == 18) {
            puesto19_obs.setText(texto);
        } else if (puesto == 19) {
            puesto20_obs.setText(texto);
        }
    }

    public void actualizarPacienteEspera(Paciente p) {
        String texto = "";
        if (p != null) {
            texto = texto + p.getIdP();
            paciente_espera.setText(texto);
        } else {
            paciente_espera.setText(texto);
        }
    }

    public void actualizarVacunas(int n) {
        String texto = String.valueOf(n);
        this.vacunas_disponibles.setText(texto);
    }
    
    public void terminarProgramaVentana () {
        this.dispose();
        System.exit(0);        
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel_espera = new javax.swing.JPanel();
        cola_espera_label = new javax.swing.JLabel();
        cola_espera = new javax.swing.JTextField();
        paciente_espera_label = new javax.swing.JLabel();
        paciente_espera = new javax.swing.JTextField();
        auxiliar1_label = new javax.swing.JLabel();
        auxiliar1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sala_descanso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panel_vacunacion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        auxiliar2_label = new javax.swing.JLabel();
        auxiliar2 = new javax.swing.JTextField();
        vacunas_disponibles_label = new javax.swing.JLabel();
        vacunas_disponibles = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        puesto6_vac = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        puesto7_vac = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        puesto8_vac = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        puesto9_vac = new javax.swing.JTextField();
        puesto10_vac = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        puesto5_vac = new javax.swing.JTextField();
        puesto4_vac = new javax.swing.JTextField();
        puesto3_vac = new javax.swing.JTextField();
        puesto2_vac = new javax.swing.JTextField();
        puesto1_vac = new javax.swing.JTextField();
        panel_observacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sanitario_observacion_label1 = new javax.swing.JLabel();
        sanitario_observacion_label2 = new javax.swing.JLabel();
        puesto2_obs = new javax.swing.JTextField();
        puesto3_obs = new javax.swing.JTextField();
        puesto1_obs = new javax.swing.JTextField();
        puesto4_obs = new javax.swing.JTextField();
        puesto5_obs = new javax.swing.JTextField();
        puesto6_obs = new javax.swing.JTextField();
        puesto7_obs = new javax.swing.JTextField();
        puesto8_obs = new javax.swing.JTextField();
        puesto10_obs = new javax.swing.JTextField();
        puesto9_obs = new javax.swing.JTextField();
        sanitario_observacion_label3 = new javax.swing.JLabel();
        sanitario_observacion_label5 = new javax.swing.JLabel();
        sanitario_observacion_label6 = new javax.swing.JLabel();
        sanitario_observacion_label4 = new javax.swing.JLabel();
        sanitario_observacion_label7 = new javax.swing.JLabel();
        sanitario_observacion_label8 = new javax.swing.JLabel();
        sanitario_observacion_label10 = new javax.swing.JLabel();
        sanitario_observacion_label9 = new javax.swing.JLabel();
        puesto11_obs = new javax.swing.JTextField();
        sanitario_observacion_label11 = new javax.swing.JLabel();
        puesto12_obs = new javax.swing.JTextField();
        sanitario_observacion_label12 = new javax.swing.JLabel();
        puesto13_obs = new javax.swing.JTextField();
        sanitario_observacion_label13 = new javax.swing.JLabel();
        puesto14_obs = new javax.swing.JTextField();
        sanitario_observacion_label14 = new javax.swing.JLabel();
        puesto15_obs = new javax.swing.JTextField();
        sanitario_observacion_label15 = new javax.swing.JLabel();
        puesto16_obs = new javax.swing.JTextField();
        sanitario_observacion_label16 = new javax.swing.JLabel();
        puesto17_obs = new javax.swing.JTextField();
        sanitario_observacion_label17 = new javax.swing.JLabel();
        puesto18_obs = new javax.swing.JTextField();
        sanitario_observacion_label18 = new javax.swing.JLabel();
        puesto19_obs = new javax.swing.JTextField();
        sanitario_observacion_label19 = new javax.swing.JLabel();
        puesto20_obs = new javax.swing.JTextField();
        sanitario_observacion_label20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL");

        cola_espera_label.setForeground(new java.awt.Color(255, 255, 255));
        cola_espera_label.setText("Cola espera");

        cola_espera.setEditable(false);
        cola_espera.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cola_espera.setForeground(new java.awt.Color(0, 0, 0));
        cola_espera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola_esperaActionPerformed(evt);
            }
        });

        paciente_espera_label.setForeground(new java.awt.Color(255, 255, 255));
        paciente_espera_label.setText("Paciente en espera");

        paciente_espera.setEditable(false);
        paciente_espera.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        paciente_espera.setForeground(new java.awt.Color(0, 0, 0));
        paciente_espera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente_esperaActionPerformed(evt);
            }
        });

        auxiliar1_label.setForeground(new java.awt.Color(255, 255, 255));
        auxiliar1_label.setText("Auxiliar");

        auxiliar1.setEditable(false);
        auxiliar1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        auxiliar1.setForeground(new java.awt.Color(0, 0, 0));
        auxiliar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxiliar1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel_esperaLayout = new org.jdesktop.layout.GroupLayout(panel_espera);
        panel_espera.setLayout(panel_esperaLayout);
        panel_esperaLayout.setHorizontalGroup(
            panel_esperaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_esperaLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(panel_esperaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(panel_esperaLayout.createSequentialGroup()
                        .add(cola_espera_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(cola_espera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panel_esperaLayout.createSequentialGroup()
                        .add(paciente_espera_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(paciente_espera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61)
                        .add(auxiliar1_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(auxiliar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panel_esperaLayout.setVerticalGroup(
            panel_esperaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_esperaLayout.createSequentialGroup()
                .addContainerGap()
                .add(panel_esperaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cola_espera, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .add(cola_espera_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panel_esperaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(auxiliar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(auxiliar1_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(paciente_espera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(paciente_espera_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recepción");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sala de descanso");

        sala_descanso.setEditable(false);
        sala_descanso.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sala_descanso.setForeground(new java.awt.Color(0, 0, 0));
        sala_descanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala_descansoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sala de vacunación");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Puesto 1");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puesto 2");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puesto 3");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Puesto 4");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Puesto 5");

        auxiliar2_label.setForeground(new java.awt.Color(255, 255, 255));
        auxiliar2_label.setText("Auxiliar");

        auxiliar2.setEditable(false);
        auxiliar2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        auxiliar2.setForeground(new java.awt.Color(0, 0, 0));
        auxiliar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxiliar2ActionPerformed(evt);
            }
        });

        vacunas_disponibles_label.setForeground(new java.awt.Color(255, 255, 255));
        vacunas_disponibles_label.setText("Vacunas Disponibles");

        vacunas_disponibles.setEditable(false);
        vacunas_disponibles.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vacunas_disponibles.setForeground(new java.awt.Color(0, 0, 0));
        vacunas_disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacunas_disponiblesActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Puesto 6");

        puesto6_vac.setEditable(false);
        puesto6_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto6_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto6_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto6_vacActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Puesto 7");

        puesto7_vac.setEditable(false);
        puesto7_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto7_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto7_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto7_vacActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Puesto 8");

        puesto8_vac.setEditable(false);
        puesto8_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto8_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto8_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto8_vacActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Puesto 9");

        puesto9_vac.setEditable(false);
        puesto9_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto9_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto9_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto9_vacActionPerformed(evt);
            }
        });

        puesto10_vac.setEditable(false);
        puesto10_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto10_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto10_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto10_vacActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Puesto 10");

        puesto5_vac.setEditable(false);
        puesto5_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto5_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto5_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto5_vacActionPerformed(evt);
            }
        });

        puesto4_vac.setEditable(false);
        puesto4_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto4_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto4_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto4_vacActionPerformed(evt);
            }
        });

        puesto3_vac.setEditable(false);
        puesto3_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto3_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto3_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto3_vacActionPerformed(evt);
            }
        });

        puesto2_vac.setEditable(false);
        puesto2_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto2_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto2_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto2_vacActionPerformed(evt);
            }
        });

        puesto1_vac.setEditable(false);
        puesto1_vac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto1_vac.setForeground(new java.awt.Color(0, 0, 0));
        puesto1_vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto1_vacActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel_vacunacionLayout = new org.jdesktop.layout.GroupLayout(panel_vacunacion);
        panel_vacunacion.setLayout(panel_vacunacionLayout);
        panel_vacunacionLayout.setHorizontalGroup(
            panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_vacunacionLayout.createSequentialGroup()
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .add(63, 63, 63)
                        .add(jLabel15)
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(panel_vacunacionLayout.createSequentialGroup()
                                .add(110, 110, 110)
                                .add(puesto7_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(80, 80, 80)
                                .add(puesto8_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(66, 66, 66)
                                .add(puesto9_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panel_vacunacionLayout.createSequentialGroup()
                                .add(139, 139, 139)
                                .add(jLabel16)
                                .add(136, 136, 136)
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel18)
                                .add(26, 26, 26)))
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panel_vacunacionLayout.createSequentialGroup()
                                .add(65, 65, 65)
                                .add(puesto10_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panel_vacunacionLayout.createSequentialGroup()
                                .add(91, 91, 91)
                                .add(jLabel19))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel_vacunacionLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(puesto6_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(puesto1_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(puesto2_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(80, 80, 80)
                        .add(puesto3_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(66, 66, 66)
                        .add(puesto4_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(65, 65, 65)
                        .add(puesto5_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .add(151, 151, 151)
                        .add(vacunas_disponibles_label)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_vacunacionLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_vacunacionLayout.createSequentialGroup()
                                .add(auxiliar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(155, 155, 155))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_vacunacionLayout.createSequentialGroup()
                                .add(vacunas_disponibles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(158, 158, 158))))))
            .add(panel_vacunacionLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jLabel8)
                .add(140, 140, 140)
                .add(jLabel9)
                .add(132, 132, 132)
                .add(jLabel10)
                .add(121, 121, 121)
                .add(jLabel11)
                .add(117, 117, 117)
                .add(jLabel12)
                .add(218, 218, 218)
                .add(auxiliar2_label)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_vacunacionLayout.setVerticalGroup(
            panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_vacunacionLayout.createSequentialGroup()
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(jLabel9)
                            .add(jLabel10)
                            .add(jLabel11)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_vacunacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(auxiliar2_label)
                        .add(3, 3, 3)))
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(puesto1_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(puesto3_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(puesto2_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(puesto4_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(puesto5_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(auxiliar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel16)
                            .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel17)
                                .add(jLabel18)
                                .add(jLabel15)
                                .add(jLabel19)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_vacunacionLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                        .add(vacunas_disponibles_label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(puesto9_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(puesto10_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(panel_vacunacionLayout.createSequentialGroup()
                        .add(panel_vacunacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(puesto6_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(puesto7_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(puesto8_vac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vacunas_disponibles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sala de observación");

        sanitario_observacion_label1.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label1.setText("Puesto 1");

        sanitario_observacion_label2.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label2.setText("Puesto 2");

        puesto2_obs.setEditable(false);
        puesto2_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto2_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto2_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto2_obsActionPerformed(evt);
            }
        });

        puesto3_obs.setEditable(false);
        puesto3_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto3_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto3_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto3_obsActionPerformed(evt);
            }
        });

        puesto1_obs.setEditable(false);
        puesto1_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto1_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto1_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto1_obsActionPerformed(evt);
            }
        });

        puesto4_obs.setEditable(false);
        puesto4_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto4_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto4_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto4_obsActionPerformed(evt);
            }
        });

        puesto5_obs.setEditable(false);
        puesto5_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto5_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto5_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto5_obsActionPerformed(evt);
            }
        });

        puesto6_obs.setEditable(false);
        puesto6_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto6_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto6_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto6_obsActionPerformed(evt);
            }
        });

        puesto7_obs.setEditable(false);
        puesto7_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto7_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto7_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto7_obsActionPerformed(evt);
            }
        });

        puesto8_obs.setEditable(false);
        puesto8_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto8_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto8_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto8_obsActionPerformed(evt);
            }
        });

        puesto10_obs.setEditable(false);
        puesto10_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto10_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto10_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto10_obsActionPerformed(evt);
            }
        });

        puesto9_obs.setEditable(false);
        puesto9_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto9_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto9_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto9_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label3.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label3.setText("Puesto 3");

        sanitario_observacion_label5.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label5.setText("Puesto 5");

        sanitario_observacion_label6.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label6.setText("Puesto 6");

        sanitario_observacion_label4.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label4.setText("Puesto 4");

        sanitario_observacion_label7.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label7.setText("Puesto 7");

        sanitario_observacion_label8.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label8.setText("Puesto 8");

        sanitario_observacion_label10.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label10.setText("Puesto 10");

        sanitario_observacion_label9.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label9.setText("Puesto 9");

        puesto11_obs.setEditable(false);
        puesto11_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto11_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto11_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto11_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label11.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label11.setText("Puesto 11");

        puesto12_obs.setEditable(false);
        puesto12_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto12_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto12_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto12_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label12.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label12.setText("Puesto 12");

        puesto13_obs.setEditable(false);
        puesto13_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto13_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto13_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto13_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label13.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label13.setText("Puesto 13");

        puesto14_obs.setEditable(false);
        puesto14_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto14_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto14_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto14_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label14.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label14.setText("Puesto 14");

        puesto15_obs.setEditable(false);
        puesto15_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto15_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto15_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto15_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label15.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label15.setText("Puesto 15");

        puesto16_obs.setEditable(false);
        puesto16_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto16_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto16_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto16_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label16.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label16.setText("Puesto 16");

        puesto17_obs.setEditable(false);
        puesto17_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto17_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto17_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto17_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label17.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label17.setText("Puesto 17");

        puesto18_obs.setEditable(false);
        puesto18_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto18_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto18_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto18_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label18.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label18.setText("Puesto 18");

        puesto19_obs.setEditable(false);
        puesto19_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto19_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto19_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto19_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label19.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label19.setText("Puesto 19");

        puesto20_obs.setEditable(false);
        puesto20_obs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        puesto20_obs.setForeground(new java.awt.Color(0, 0, 0));
        puesto20_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto20_obsActionPerformed(evt);
            }
        });

        sanitario_observacion_label20.setForeground(new java.awt.Color(255, 255, 255));
        sanitario_observacion_label20.setText("Puesto 20");

        org.jdesktop.layout.GroupLayout panel_observacionLayout = new org.jdesktop.layout.GroupLayout(panel_observacion);
        panel_observacion.setLayout(panel_observacionLayout);
        panel_observacionLayout.setHorizontalGroup(
            panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_observacionLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(puesto1_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto2_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23)
                        .add(puesto3_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto4_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto5_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto6_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto7_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(puesto11_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26)
                        .add(puesto12_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto13_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto14_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto15_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panel_observacionLayout.createSequentialGroup()
                                .add(sanitario_observacion_label16)
                                .add(72, 72, 72)
                                .add(sanitario_observacion_label17))
                            .add(panel_observacionLayout.createSequentialGroup()
                                .add(puesto16_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(puesto17_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(sanitario_observacion_label11)
                        .add(78, 78, 78)
                        .add(sanitario_observacion_label12)
                        .add(54, 54, 54)
                        .add(sanitario_observacion_label13)
                        .add(68, 68, 68)
                        .add(sanitario_observacion_label14)
                        .add(63, 63, 63)
                        .add(sanitario_observacion_label15)))
                .add(18, 18, 18)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(puesto18_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto19_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(puesto20_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(puesto8_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(sanitario_observacion_label18))
                        .add(18, 18, 18)
                        .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(puesto9_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(sanitario_observacion_label19))
                        .add(18, 18, 18)
                        .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(sanitario_observacion_label20)
                            .add(puesto10_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 55, Short.MAX_VALUE))
            .add(panel_observacionLayout.createSequentialGroup()
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(488, 488, 488)
                        .add(jLabel2))
                    .add(panel_observacionLayout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(sanitario_observacion_label1)
                        .add(78, 78, 78)
                        .add(sanitario_observacion_label2)
                        .add(78, 78, 78)
                        .add(sanitario_observacion_label3)
                        .add(71, 71, 71)
                        .add(sanitario_observacion_label4)
                        .add(71, 71, 71)
                        .add(sanitario_observacion_label5)
                        .add(75, 75, 75)
                        .add(sanitario_observacion_label6)
                        .add(78, 78, 78)
                        .add(sanitario_observacion_label7)
                        .add(69, 69, 69)
                        .add(sanitario_observacion_label8)
                        .add(58, 58, 58)
                        .add(sanitario_observacion_label9)
                        .add(82, 82, 82)
                        .add(sanitario_observacion_label10)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_observacionLayout.setVerticalGroup(
            panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_observacionLayout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel2)
                .add(34, 34, 34)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sanitario_observacion_label1)
                    .add(sanitario_observacion_label2)
                    .add(sanitario_observacion_label3)
                    .add(sanitario_observacion_label5)
                    .add(sanitario_observacion_label6)
                    .add(sanitario_observacion_label4)
                    .add(sanitario_observacion_label7)
                    .add(sanitario_observacion_label8)
                    .add(sanitario_observacion_label10)
                    .add(sanitario_observacion_label9))
                .add(18, 18, 18)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(puesto2_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto3_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto1_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto4_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto5_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto6_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto7_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto8_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto10_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto9_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sanitario_observacion_label11)
                    .add(sanitario_observacion_label12)
                    .add(sanitario_observacion_label13)
                    .add(sanitario_observacion_label15)
                    .add(sanitario_observacion_label16)
                    .add(sanitario_observacion_label14)
                    .add(sanitario_observacion_label17)
                    .add(sanitario_observacion_label18)
                    .add(sanitario_observacion_label20)
                    .add(sanitario_observacion_label19))
                .add(18, 18, 18)
                .add(panel_observacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(puesto12_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto13_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto11_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto14_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto15_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto16_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto17_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto18_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto20_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(puesto19_obs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(241, 241, 241)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(463, 463, 463)
                .add(jLabel6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(panel_vacunacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(panel_observacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(panel_espera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(161, 161, 161)
                                .add(sala_descanso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 373, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(505, 505, 505)
                                .add(jLabel7))
                            .add(layout.createSequentialGroup()
                                .add(517, 517, 517)
                                .add(jLabel1)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel_espera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sala_descanso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel7)
                .add(18, 18, 18)
                .add(panel_vacunacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel_observacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puesto10_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto10_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto10_vacActionPerformed

    private void auxiliar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxiliar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxiliar2ActionPerformed

    private void puesto2_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto2_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto2_obsActionPerformed

    private void sala_descansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala_descansoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala_descansoActionPerformed

    private void puesto6_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto6_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto6_vacActionPerformed

    private void puesto7_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto7_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto7_vacActionPerformed

    private void puesto8_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto8_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto8_vacActionPerformed

    private void puesto9_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto9_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto9_vacActionPerformed

    private void vacunas_disponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacunas_disponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacunas_disponiblesActionPerformed

    private void puesto1_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto1_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto1_obsActionPerformed

    private void puesto3_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto3_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto3_obsActionPerformed

    private void puesto4_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto4_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto4_obsActionPerformed

    private void puesto5_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto5_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto5_obsActionPerformed

    private void puesto6_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto6_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto6_obsActionPerformed

    private void puesto7_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto7_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto7_obsActionPerformed

    private void puesto8_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto8_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto8_obsActionPerformed

    private void puesto9_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto9_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto9_obsActionPerformed

    private void puesto10_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto10_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto10_obsActionPerformed

    private void puesto11_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto11_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto11_obsActionPerformed

    private void puesto12_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto12_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto12_obsActionPerformed

    private void puesto13_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto13_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto13_obsActionPerformed

    private void puesto14_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto14_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto14_obsActionPerformed

    private void puesto15_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto15_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto15_obsActionPerformed

    private void puesto16_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto16_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto16_obsActionPerformed

    private void puesto17_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto17_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto17_obsActionPerformed

    private void puesto18_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto18_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto18_obsActionPerformed

    private void puesto19_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto19_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto19_obsActionPerformed

    private void puesto20_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto20_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto20_obsActionPerformed

    private void auxiliar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxiliar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxiliar1ActionPerformed

    private void paciente_esperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente_esperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente_esperaActionPerformed

    private void cola_esperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola_esperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola_esperaActionPerformed

    private void puesto5_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto5_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto5_vacActionPerformed

    private void puesto4_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto4_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto4_vacActionPerformed

    private void puesto3_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto3_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto3_vacActionPerformed

    private void puesto2_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto2_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto2_vacActionPerformed

    private void puesto1_vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto1_vacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puesto1_vacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auxiliar1;
    private javax.swing.JLabel auxiliar1_label;
    private javax.swing.JTextField auxiliar2;
    private javax.swing.JLabel auxiliar2_label;
    private javax.swing.JTextField cola_espera;
    private javax.swing.JLabel cola_espera_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField paciente_espera;
    private javax.swing.JLabel paciente_espera_label;
    private javax.swing.JPanel panel_espera;
    private javax.swing.JPanel panel_observacion;
    private javax.swing.JPanel panel_vacunacion;
    private javax.swing.JTextField puesto10_obs;
    private javax.swing.JTextField puesto10_vac;
    private javax.swing.JTextField puesto11_obs;
    private javax.swing.JTextField puesto12_obs;
    private javax.swing.JTextField puesto13_obs;
    private javax.swing.JTextField puesto14_obs;
    private javax.swing.JTextField puesto15_obs;
    private javax.swing.JTextField puesto16_obs;
    private javax.swing.JTextField puesto17_obs;
    private javax.swing.JTextField puesto18_obs;
    private javax.swing.JTextField puesto19_obs;
    private javax.swing.JTextField puesto1_obs;
    private javax.swing.JTextField puesto1_vac;
    private javax.swing.JTextField puesto20_obs;
    private javax.swing.JTextField puesto2_obs;
    private javax.swing.JTextField puesto2_vac;
    private javax.swing.JTextField puesto3_obs;
    private javax.swing.JTextField puesto3_vac;
    private javax.swing.JTextField puesto4_obs;
    private javax.swing.JTextField puesto4_vac;
    private javax.swing.JTextField puesto5_obs;
    private javax.swing.JTextField puesto5_vac;
    private javax.swing.JTextField puesto6_obs;
    private javax.swing.JTextField puesto6_vac;
    private javax.swing.JTextField puesto7_obs;
    private javax.swing.JTextField puesto7_vac;
    private javax.swing.JTextField puesto8_obs;
    private javax.swing.JTextField puesto8_vac;
    private javax.swing.JTextField puesto9_obs;
    private javax.swing.JTextField puesto9_vac;
    private javax.swing.JTextField sala_descanso;
    private javax.swing.JLabel sanitario_observacion_label1;
    private javax.swing.JLabel sanitario_observacion_label10;
    private javax.swing.JLabel sanitario_observacion_label11;
    private javax.swing.JLabel sanitario_observacion_label12;
    private javax.swing.JLabel sanitario_observacion_label13;
    private javax.swing.JLabel sanitario_observacion_label14;
    private javax.swing.JLabel sanitario_observacion_label15;
    private javax.swing.JLabel sanitario_observacion_label16;
    private javax.swing.JLabel sanitario_observacion_label17;
    private javax.swing.JLabel sanitario_observacion_label18;
    private javax.swing.JLabel sanitario_observacion_label19;
    private javax.swing.JLabel sanitario_observacion_label2;
    private javax.swing.JLabel sanitario_observacion_label20;
    private javax.swing.JLabel sanitario_observacion_label3;
    private javax.swing.JLabel sanitario_observacion_label4;
    private javax.swing.JLabel sanitario_observacion_label5;
    private javax.swing.JLabel sanitario_observacion_label6;
    private javax.swing.JLabel sanitario_observacion_label7;
    private javax.swing.JLabel sanitario_observacion_label8;
    private javax.swing.JLabel sanitario_observacion_label9;
    private javax.swing.JTextField vacunas_disponibles;
    private javax.swing.JLabel vacunas_disponibles_label;
    // End of variables declaration//GEN-END:variables

}
